### ISSUE TITLE
Fails with `magit-git-dir` related error

### ISSUE THREAD

**Issue by arnab** [maio/helm-git#5]
Just installed this on Emacs24. I was already using `magit-1.1.1`.

`helm-git-find-files` kept failing with an error like:

```
magit-git-dir: Symbol's function definition is void
```

Has that function been removed from magit?

**Comment by maio** [comment]
Hello. Sorry for slow reply. Somehow I missed notification. :(

I no longer use this package - would it be OK for you to switch to helm-ls-files which is being maintained? https://github.com/emacs-helm/helm-ls-git

**Comment by arnab** [comment]
Thanks - yes I have already moved on to `helm-ls-git`.
