### ISSUE TITLE
(void-variable helm-c-source-find-files)

### ISSUE THREAD

**Issue by sungwonida** [maio/helm-git#6]
Hi Marian,
I just updated packages related to helm through melpa and I get error starting Emacs saying (void-variable helm-c-source-find-files).
I found that there were two 'helm-c-source-find-files' in helm-git.el and I modified them as 'helm-source-find-files'. But I came to get another error. I attatched the top of backtrace log.

> Debugger entered--Lisp error: (error "No buffer named *helm*")
>   helm-get-current-source()
>   helm-attr(action nil ignorefn)
>   helm-add-action-to-source-if("List git files" helm-ff-git-find-files nil helm-git-root-p 4)
>   (progn (helm-add-action-to-source-if "List git files" (quote helm-ff-git-find-files) helm-source-find-files (quote helm-git-root-p) helm-git-ff-action-index))
>   (if (require (quote helm-files)) (progn (helm-add-action-to-source-if "List git files" (quote helm-ff-git-find-files) helm-source-find-files (quote helm-git-root-p) helm-git-ff-action-index)))
>   eval-buffer(#<buffer  *load*-355188> nil "/home/david/.emacs.d/.cask/25.2/elpa/helm-git-20120630.1403/helm-git.el" nil t)  ; Reading at buffer position 3678
>   load-with-code-conversion("/home/david/.emacs.d/.cask/25.2/elpa/helm-git-20120630.1403/helm-git.el" "/home/david/.emacs.d/.cask/25.2/elpa/helm-git-20120630.1403/helm-git.el" t t)
>   require(helm-git nil t)

**Comment by maio** [comment]
Hi David,

this package is deprecated. Is it possible for you to switch to https://github.com/emacs-helm/helm-ls-git  ?

**Comment by sungwonida** [comment]
Aha.. thank you for letting me know, Marian. 
helm-ls-git looks working pretty well, thanks again!
